{{- if .Values.pooler.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "cnpg-postgres.clusterName" . }}-pooler-rw
  namespace: {{ include "cnpg-postgres.namespace" . }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "cnpg-postgres.clusterName" . }}
  instances: {{ .Values.pooler.instances }}
  type: rw
  pgbouncer:
    poolMode: {{ .Values.pooler.poolMode }}
    parameters:
      {{- toYaml .Values.pooler.parameters | nindent 6 }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "cnpg-postgres.clusterName" . }}-pooler-ro
  namespace: {{ include "cnpg-postgres.namespace" . }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "cnpg-postgres.clusterName" . }}
  instances: {{ .Values.pooler.instances }}
  type: ro
  pgbouncer:
    poolMode: {{ .Values.pooler.poolMode }}
    parameters:
      {{- toYaml .Values.pooler.parameters | nindent 6 }}
{{- end }}
