apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.clusterName" . }}-superuser
  namespace: {{ include "cnpg-postgres.namespace" . }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.superuser.username }}
  password: {{ .Values.secrets.superuser.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.clusterName" . }}-app-credentials
  namespace: {{ include "cnpg-postgres.namespace" . }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.appuser.username }}
  password: {{ .Values.secrets.appuser.password }}
{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.clusterName" . }}-backup-creds
  namespace: {{ include "cnpg-postgres.namespace" . }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.backup.s3.accessKeyId }}
  SECRET_ACCESS_KEY: {{ .Values.backup.s3.secretAccessKey }}
{{- end }}
