apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oracle-xe.fullname" . }}-secret
  namespace: {{ include "oracle-xe.namespace" . }}
  labels:
    {{- include "oracle-xe.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORACLE_PWD: {{ .Values.oracle.password }}
  ORACLE_CHARACTERSET: {{ .Values.oracle.characterSet }}
