apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBIT_USER: {{ .Values.rabbitmq.user }}
  RABBIT_PASS: {{ .Values.rabbitmq.password }}
  RABBIT_VHOST: {{ .Values.rabbitmq.vhost }}
